name = "server-radar"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-11-01"

[placement]
mode = "off"

[[d1_databases]]
database_id = "1138185b-a1aa-4d0b-96f8-7e1388b91a2a"
binding = "DB"
database_name = "DB"

[env.production]
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
services = [
  { binding = "RATE_LIMIT", service = "rate-limiter" }
]

[env.production.placement]
mode = "smart"

[[env.production.vars]]
NODE_VERSION = "22"

[[env.production.d1_databases]]
database_id = "1138185b-a1aa-4d0b-96f8-7e1388b91a2a"
binding = "DB"
database_name = "DB"

[env.production.queues]
producers=[
  { queue = "email-queue", binding = "EMAIL_QUEUE" }
]